### ISSUE TITLE
运行有错误

### ISSUE THREAD

**Issue by jinbooooom** [sailist/MarkTex#4]
ubuntu 16.04。
创建了一个文件夹a，测试将 README.md 转换成 pdf。

```shell
$ pip install marktex -i https://pypi.python.org/pypi
$ marktex README.md -o "a"
Traceback (most recent call last):
  File "/home/jinbo/anaconda3/bin/marktex", line 7, in <module>
    from marktex.cli import main
  File "/home/jinbo/anaconda3/lib/python3.5/site-packages/marktex/cli.py", line 88
    print(f"[info*]convert finished.")
                                    ^
SyntaxError: invalid syntax
```
尝试运行 run_example.py 也报错了

```shell
$ python3 run_example.py 
Traceback (most recent call last):
  File "run_example.py", line 1, in <module>
    from marktex import api
  File "/home/jinbo/gitme/MarkTex/marktex/api.py", line 2, in <module>
    from marktex.util import config
  File "/home/jinbo/gitme/MarkTex/marktex/util.py", line 38
    newf = os.path.join(fdir, f"{mmd.hexdigest()}.{ext}")
```

**Comment by sailist** [comment]
Python3.5 不支持这种format方法...之前没注意，新提交了，可以通过 `pip3 install -U marktex ` 重新安装
